#!/bin/sh

set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.profile" "$HOME/.profile"

mkdir -p "$HOME/.local/bin" || true
ln -sf "$PWD/scripts" "$HOME/.local/bin/scripts"

for i in vim lynx gh git tmux; do
  cd $i && ./setup
  cd -
done

ln -sf "$PWD/shell.d" "$HOME/.shell.d"

