#!/bin/sh

set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.xinitrc" "$HOME/.xinitrc"

mkdir -p "$HOME/.local/bin" || true

for i in alacritty vim lynx gh git tmux; do
  cd $i && ./setup
  cd -
done

ln -sf "$PWD/shell.d" "$HOME/.shell.d"

