#!/bin/sh

WEECHAT_FIFO="/run/user/1000/weechat/weechat_fifo_3410652"
buf="$*"

if [ -n "$buf" ]; then
  echo "*$buf"  > $WEECHAT_FIFO
  exit 0
fi

while IFS= read -r line; do
  echo "*$line" > $WEECHAT_FIFO
done

